# I was attempting to debug a segfault on 32-bit Linux (did not even test 32-bit Windows yet)
# but we decided against providing XGBoost for 32-bit OSes instead. Anyway, this attempt failed
# because python and R bake their compilation flags into sysconfigdata.py and lib/R/etc/Makeconf
# respectively and I did not build debug versions of python nor r-base.
# c_compiler:
#   - clang-dbg                  # [osx]
#   - gcc-dbg                    # [linux]
# cxx_compiler:
#   - clangxx-dbg                # [osx]
#   - gxx-dbg                    # [linux]
# fortran_compiler:
#   - gfortran-dbg               # [linux]
python:
  - 2.7
  - 3.5
  - 3.6
r_implementation:
  - r-base
  - mro-base  # [not osx and not linux32 and not win32]
