# abseil now only support MacOS >=10.13, see
# https://github.com/abseil/abseil-cpp#support and
# https://github.com/abseil/abseil-cpp/issues/1513
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - "10.13"                # [osx]
MACOSX_SDK_VERSION:        # [osx]
  - "10.13"                # [osx]
