{% set name = "xgboost" %}
{% set version = "0.90" %}

{% set xgboost_proc_type = "cpu" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # we have to use git urls here to get the submodules needed for the
  # build
  git_url: https://github.com/dmlc/xgboost
  git_tag: 515f5f5c4779ff5361dcd796e22d55937e1048ea
  patches:
    # xgboost patches
    - 0001-conda-Unbundle-libxgboost.-dll-dylib-so.patch
    - 0002-Fix-R-package-PKGROOT.patch
    - 0003-Fix-R-package-mingw-w64-compiler-flags-remove-m64.patch

build:
  number: 5
  skip: true  # [win or linux32 or py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
    - cmake
    - make
    - llvm-openmp  # [osx]
  host:
    - llvm-openmp  # [osx]

outputs:
  - name: xgboost-proc
    version: 1.0.0
    build:
      number: 0
      string: "{{ xgboost_proc_type }}"
    test:
      commands:
        - exit 0
    about:
      home: https://github.com/conda-forge/xgboost-feedstock
      license: BSD-3-Clause
      license_family: BSD
      summary: A meta-package to select CPU or GPU xgboost build.

  - name: libxgboost
    script: install-libxgboost.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - git
        - cmake
        - make
        - llvm-openmp  # [osx]
      host:
        - llvm-openmp  # [osx]
      run:
        - llvm-openmp  # [osx]
      run_constrained:
        - xgboost-proc * {{ xgboost_proc_type }}

  - name: py-xgboost
    script: install-py-xgboost.sh
    requirements:
      host:
        - {{ pin_subpackage('libxgboost', exact=True) }}
        - python
        - setuptools
        - pip
      run:
        - {{ pin_subpackage('libxgboost', exact=True) }}
        - python
        - numpy
        - scipy
        - scikit-learn
    test:
      script: test-py-xgboost.py
      imports:
        - xgboost

  - name: xgboost
    requirements:
      host:
        - python
        # we install llvm-opnemp here to convince conda to
        # install llvm-openmp in the top-level host env above
        - llvm-openmp  # [osx]
      run:
        - python
        - {{ pin_subpackage('py-xgboost', exact=True) }}

  - name: r-xgboost
    script: install-r-xgboost.sh
    build:
      rpaths:
        - lib/R/lib
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - git
        - cmake
        - make
        - llvm-openmp  # [osx]
      host:
        - {{ pin_subpackage('libxgboost', exact=True) }}
        - r-base
        - llvm-openmp  # [osx]
        - r-matrix
        - r-data.table
        - r-magrittr
        - r-stringi
        - r-knitr
      run:
        - {{ pin_subpackage('libxgboost', exact=True) }}
        - llvm-openmp  # [osx]
        - r-base
        - r-matrix
        - r-data.table
        - r-magrittr
        - r-stringi
    test:
      files:
        - test-r-xgboost.r
      commands:
        - Rscript test-r-xgboost.r

about:
  home: https://github.com/dmlc/xgboost
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    Scalable, Portable and Distributed Gradient Boosting (GBDT, GBRT or GBM) Library, for
    Python, R, Java, Scala, C++ and more. Runs on single machine, Hadoop, Spark, Flink
    and DataFlow
  description: |
    XGBoost is an optimized distributed gradient boosting library designed to be highly efficient,
    flexible and portable. It implements machine learning algorithms under the Gradient Boosting
    framework. XGBoost provides a parallel tree boosting (also known as GBDT, GBM) that solve many
    data science problems in a fast and accurate way. The same code runs on major distributed
    environment (Hadoop, SGE, MPI) and can solve problems beyond billions of examples.
  doc_url: https://xgboost.readthedocs.io/
  dev_url: https://github.com/dmlc/xgboost/

extra:
  recipe-maintainers:
    - aldanor
    - beckermr
    - jakirkham
