azure:
  free_disk_space: true
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
channel_priority: flexible
conda_build:
  error_overlinking: true
  pkg_format: '2'
conda_build_tool: conda-build
conda_forge_output_validation: false
conda_install_tool: mamba
conda_solver: libmamba
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  artifact_retention_days: 7
  free_disk_space: true
  upload_packages: true
provider:
  linux: github_actions
  linux_aarch64: github_actions
  osx: github_actions
  win: github_actions
test_on_native_only: true
