appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jQqVfXiLD/zctXLS4sj+fxOnB/hiIY4MmdJtQfY9aupAwW9MKkfPNO61LL0wJAOCHHOTyWG5CDNP16OstXwJWM06GZchgrrKriVQWnKLolwhDnNAN27/JbEHlXguXjfjxAiws/rdECb7uHDU+fQN+KxE18aiDi9QkkAhWArIQK1udndHoQM3lbvDbMVO7GakiqH7f3GdHUhsQjtDh0IPIxUl9VA3mfVJuSHnSC2IMSdbAUVS35gbKK+LatxcvwbNUXNpzGjuYAcellx3jCm0O+0MLln8A8YSUVxj2tB8EPhzC4Oyd+s/Vp8ROBcNrcrWN1Q4hYywxiPeA2Nf7+BjeDknA9Ha5P5eLVCMFwRLTrQFcZc2l5utTa8H2mdXYn9G28SlJnNIQEXIYmtZQYSFlHgFrPgo3SU1ABCUy+wgjqiXUNTgeurMybsv3ppafFqNbyD6wdCTQARiE1xI4zGANhUsaIBWcVUoXI7pbfQM+SpLUZiDSDpe0EuoI7iblBWQmRyxVaTc4pYCWNMu/ROeaAgaQu/pg9mpd82N6MVc3DSdm2opTRyDglCW/DrCmyVk6hVvB1zRgiRLMAnzhGMlyhXfDW9DvtJCPjwY9xfHJNprMblhYR+iT260xqs2HTqsaBhhBVn0UKvPFXKGSI+ld6aUFpAR45VAMx/SP5Q2Udc=}
